import uuid
import logging
import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, Response, BackgroundTasks

from app.core.auth import get_current_user
from app.services.nlp.pipeline import run_nlp_pipeline
from app.services.agents.generation import run_agent_swarm
from app.core.db import get_db
from app.models.spec_db import ProjectModel, SpecModel, PipelineRunModel, ProfileModel, PricingPlanModel
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

# -------------------------------------------------------------
# Request & Response Schemas
# -------------------------------------------------------------

class ProjectCreate(BaseModel):
    name: str

class SpecCreate(BaseModel):
    project_id: str
    title: str
    content: str

class PipelineRunRequest(BaseModel):
    project_id: str
    spec_id: str
    stack: str = "fastapi+supabase"
    spec_content: str

class ProfileUpdate(BaseModel):
    username: Optional[str] = None
    full_name: Optional[str] = None
    avatar_url: Optional[str] = None

# -------------------------------------------------------------
# Helpers
# -------------------------------------------------------------

def save_run_in_background(
    run_id: str,
    project_id: str,
    spec_id: str,
    uid: str,
    spec_content: str,
    result: Dict[str, Any]
):
    from app.core.db import SessionLocal
    db = SessionLocal()
    try:
        # Verify/ensure the spec exists in SQL Database
        existing_spec = db.query(SpecModel).filter(SpecModel.id == spec_id).first()
        if not existing_spec:
            existing_spec = SpecModel(
                id=spec_id,
                project_id=project_id,
                title="Generated Spec",
                content=spec_content,
                source_type="manual",
                user_id=uid
            )
            db.add(existing_spec)
            db.commit()
            
        new_run = PipelineRunModel(
            id=run_id,
            project_id=project_id,
            spec_id=spec_id,
            user_id=uid,
            status="completed",
            stages={
                "stages": [
                    {"name": stage, "completed": True, "timestamp": datetime.datetime.utcnow().isoformat()}
                    for stage in [
                        "Requirements & scope", "Domain model", "API surface", 
                        "Workflows & states", "Data storage", "Security & compliance", 
                        "Observability", "Reliability & DR", "Scaling & performance", "Deployment & DevOps"
                    ]
                ]
            },
            result=result,
            completed_at=datetime.datetime.utcnow()
        )
        db.add(new_run)
        db.commit()
        logger.info(f"Successfully saved run {run_id} and spec {spec_id} to SQL database in the background.")
    except Exception as db_err:
        db.rollback()
        logger.error(f"Failed to save generated spec or run to database in background: {db_err}")
    finally:
        db.close()

def generate_code_skeleton(spec) -> Dict[str, str]:
    # Models skeleton
    models_code = "# SQLAlchemy models generated by Baxel\n\n"
    models_code += "from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Boolean\n"
    models_code += "from sqlalchemy.orm import relationship, declarative_base\n\nBase = declarative_base()\n\n"
    
    for table in spec.database.tables:
        models_code += f"class {table.name.title().replace('_', '')}(Base):\n"
        models_code += f"    __tablename__ = '{table.name}'\n"
        models_code += f"    # {table.description}\n\n"
        for col in table.columns:
            col_type = col.type.upper()
            if "UUID" in col_type:
                type_str = "String(36)"
            elif "INT" in col_type:
                type_str = "Integer"
            elif "DATE" in col_type or "TIME" in col_type:
                type_str = "DateTime"
            elif "BOOL" in col_type:
                type_str = "Boolean"
            else:
                type_str = "String(255)"
                
            args = []
            if col.is_primary_key:
                args.append("primary_key=True")
            if not col.is_nullable:
                args.append("nullable=False")
            if col.foreign_key:
                args.append(f"ForeignKey('{col.foreign_key}')")
                
            args_str = ", ".join(args)
            models_code += f"    {col.name} = Column({type_str}{', ' + args_str if args_str else ''})\n"
        models_code += "\n"
        
    # Routers skeleton
    routers_code = "# FastAPI routers generated by Baxel\n\n"
    routers_code += "from fastapi import APIRouter, Depends, HTTPException\n"
    routers_code += "from typing import List\n\nrouter = APIRouter()\n\n"
    
    for ep in spec.endpoints:
        normalized_name = ep.summary.lower().replace(" ", "_").replace("/", "_").replace("-", "_")
        routers_code += f"@router.{ep.method.lower()}('{ep.path}', summary='{ep.summary}')\n"
        routers_code += f"async def {normalized_name}(\n"
        if ep.is_protected:
            routers_code += "    current_user = Depends(get_current_user)\n"
        routers_code += "):\n"
        routers_code += f"    # TODO: Implement endpoint\n"
        routers_code += f"    return {{'message': '{ep.summary}'}}\n\n"
        
    return {
        "models": models_code,
        "routers": routers_code,
        "services": "# Business logic & helpers\n"
    }

def generate_migration_sql(spec) -> str:
    sql = "-- DB migration script generated by Baxel\n\n"
    for table in spec.database.tables:
        sql += f"CREATE TABLE IF NOT EXISTS {table.name} (\n"
        cols = []
        for col in table.columns:
            col_type = col.type.upper()
            if "UUID" in col_type:
                db_type = "UUID"
            elif "INT" in col_type:
                db_type = "INTEGER"
            elif "DATE" in col_type or "TIME" in col_type:
                db_type = "TIMESTAMP"
            elif "BOOL" in col_type:
                db_type = "BOOLEAN"
            else:
                db_type = "VARCHAR(255)"
                
            constraints = []
            if col.is_primary_key:
                constraints.append("PRIMARY KEY")
            if not col.is_nullable:
                constraints.append("NOT NULL")
            if col.foreign_key:
                constraints.append(f"REFERENCES {col.foreign_key.split('.')[0]}(id)")
                
            cols.append(f"    {col.name} {db_type} {' '.join(constraints)}".strip())
        sql += ",\n".join(cols)
        sql += "\n);\n\n"
    return sql

# -------------------------------------------------------------
# Routers definition
# -------------------------------------------------------------

projects_router = APIRouter(prefix="/projects", tags=["projects"])
specs_router = APIRouter(prefix="/specs", tags=["specs"])
pipelines_router = APIRouter(prefix="/pipelines", tags=["pipelines"])
dashboard_router = APIRouter(prefix="/dashboard", tags=["dashboard"])
profile_router = APIRouter(prefix="/profile", tags=["profile"])
runs_router = APIRouter(prefix="/runs", tags=["runs"])

# --- Profile Router ---
@profile_router.get("/me")
async def profile_me(user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    email = user.get("email")
    
    # Try to find the profile in the database
    profile = db.query(ProfileModel).filter(ProfileModel.id == uid).first()
    if not profile:
        profile = ProfileModel(
            id=uid,
            email=email,
            username=email.split("@")[0] if email else "user",
            full_name=email.split("@")[0].title() if email else "User",
            plan_code="starter"  # Default plan is starter
        )
        try:
            db.add(profile)
            db.commit()
            db.refresh(profile)
        except Exception as e:
            db.rollback()
            logger.error(f"Failed to auto-create profile: {e}")
            
    return {
        "id": profile.id if profile else uid,
        "email": profile.email if profile else email,
        "username": profile.username if profile else (email.split("@")[0] if email else "user"),
        "full_name": profile.full_name if profile else (email.split("@")[0].title() if email else "User"),
        "avatar_url": profile.avatar_url if profile else None,
        "plan_code": profile.plan_code if profile else "starter"
    }

@profile_router.patch("/me")
async def update_profile(
    payload: ProfileUpdate, 
    user=Depends(get_current_user), 
    db: Session = Depends(get_db)
):
    uid = user.get("sub")
    profile = db.query(ProfileModel).filter(ProfileModel.id == uid).first()
    if not profile:
        email = user.get("email")
        profile = ProfileModel(
            id=uid,
            email=email,
            username=payload.username or (email.split("@")[0] if email else "user"),
            full_name=payload.full_name or (email.split("@")[0].title() if email else "User"),
            plan_code="starter"
        )
        db.add(profile)
    else:
        if payload.username is not None:
            if payload.username.strip():
                existing = db.query(ProfileModel).filter(
                    ProfileModel.username == payload.username.strip().lower(),
                    ProfileModel.id != uid
                ).first()
                if existing:
                    raise HTTPException(status_code=400, detail="Username is already taken")
            profile.username = payload.username.strip().lower() or None
        if payload.full_name is not None:
            profile.full_name = payload.full_name.strip() or None
        if payload.avatar_url is not None:
            profile.avatar_url = payload.avatar_url.strip() or None
            
    profile.updated_at = datetime.datetime.utcnow()
    
    try:
        db.commit()
        db.refresh(profile)
    except HTTPException:
        raise
    except Exception as e:
        db.rollback()
        logger.error(f"Failed to update profile: {e}")
        raise HTTPException(status_code=500, detail="Failed to save profile changes")
        
    return {
        "id": profile.id,
        "email": profile.email,
        "username": profile.username,
        "full_name": profile.full_name,
        "avatar_url": profile.avatar_url,
        "plan_code": profile.plan_code
    }

@profile_router.get("/plan")
async def profile_plan(user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    runs_count = db.query(PipelineRunModel).filter(PipelineRunModel.user_id == uid).count()
    projects_count = db.query(ProjectModel).filter(ProjectModel.user_id == uid).count()
    
    # Get user plan_code from profiles table
    profile = db.query(ProfileModel).filter(ProfileModel.id == uid).first()
    plan_code = (profile.plan_code or "starter") if profile else "starter"
    
    # Get plan details from pricing_plans table
    plan = db.query(PricingPlanModel).filter(PricingPlanModel.code == plan_code).first()
    if plan:
        plan_name = f"{plan.display_name} Plan"
        monthly_run_limit = plan.monthly_run_limit
        monthly_project_limit = plan.monthly_project_limit
    else:
        # Fallback to starter plan limits
        plan_name = "Starter Plan"
        monthly_run_limit = 9
        monthly_project_limit = 3
        
    char_limit_map = {
        "starter": 1000,
        "creator": 1500,
        "studio": 3000,
        "growth": 9000,
        "enterprise": 15000
    }
    idea_char_limit = char_limit_map.get(plan_code.lower(), 1000)
    
    return {
        "plan_code": plan_code,
        "plan_name": plan_name,
        "status": "active",
        "monthly_run_limit": monthly_run_limit,
        "runs_used_this_month": runs_count,
        "monthly_project_limit": monthly_project_limit,
        "projects_used_this_month": projects_count,
        "runs_per_project_limit": 100,
        "idea_char_limit": idea_char_limit,
        "billing_period": None,
        "period_start": None,
        "period_end": None,
        "manage_url": None
    }

# --- Dashboard Router ---
@dashboard_router.get("/summary")
async def dashboard_summary(user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    user_projects = db.query(ProjectModel).filter(ProjectModel.user_id == uid).all()
    user_runs = db.query(PipelineRunModel).filter(PipelineRunModel.user_id == uid).all()
    
    # Enrich recent pipeline runs with spec_title and project_name
    enriched_runs = []
    for r in user_runs[-5:]:  # last 5 runs
        spec_title = "Generated Specification"
        project_name = "Default Project"
        
        if r.spec_id:
            spec = db.query(SpecModel).filter(SpecModel.id == r.spec_id).first()
            if spec:
                spec_title = spec.title
            
        proj = db.query(ProjectModel).filter(ProjectModel.id == r.project_id).first()
        if proj:
            project_name = proj.name
            
        enriched_runs.append({
            "id": r.id,
            "status": r.status,
            "created_at": r.created_at.isoformat() if isinstance(r.created_at, datetime.datetime) else str(r.created_at),
            "spec_title": spec_title,
            "project_name": project_name,
            "spec_id": r.spec_id
        })
        
    return {
        "projects_count": len(user_projects),
        "specs_count": db.query(SpecModel).filter(SpecModel.user_id == uid).count(),
        "pipeline_runs_count": len(user_runs),
        "recent_projects": [
            {
                "id": p.id,
                "name": p.name,
                "created_at": p.created_at.isoformat() if isinstance(p.created_at, datetime.datetime) else str(p.created_at)
            }
            for p in user_projects[-5:]
        ],
        "recent_pipeline_runs": enriched_runs[::-1]
    }

@dashboard_router.get("/public-metrics")
async def dashboard_public_metrics(db: Session = Depends(get_db)):
    specs_count = db.query(SpecModel).count()
    runs_count = db.query(PipelineRunModel).count()
    return {
        "specs_processed": max(15, specs_count),
        "schemas_generated": max(12, runs_count),
        "api_endpoints": 96,
        "rules_captured": 45
    }

# --- Projects Router ---
@projects_router.get("/history")
async def get_projects_history(user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    user_projects = db.query(ProjectModel).filter(ProjectModel.user_id == uid).all()
    
    result = []
    for project in user_projects:
        specs_count = db.query(SpecModel).filter(SpecModel.project_id == project.id).count()
        runs = db.query(PipelineRunModel).filter(
            PipelineRunModel.project_id == project.id,
            PipelineRunModel.status == "completed"
        ).all()
        
        recent_runs = []
        for r in runs:
            spec_title = "Generated Specification"
            if r.spec_id:
                spec = db.query(SpecModel).filter(SpecModel.id == r.spec_id).first()
                if spec:
                    spec_title = spec.title
                    
            recent_runs.append({
                "id": r.id,
                "status": r.status,
                "created_at": r.created_at.isoformat() if r.created_at else "",
                "spec_id": r.spec_id,
                "spec_title": spec_title,
                "result": r.result
            })
            
        result.append({
            "project": {
                "id": project.id,
                "name": project.name,
                "description": project.description,
                "created_at": project.created_at.isoformat() if project.created_at else ""
            },
            "specs_count": specs_count,
            "pipeline_runs_count": len(runs),
            "recent_runs": recent_runs[::-1][:20]
        })
        
    return result

@projects_router.post("")
async def create_project(payload: ProjectCreate, user=Depends(get_current_user), db: Session = Depends(get_db)):
    new_project = ProjectModel(
        id=str(uuid.uuid4()),
        name=payload.name,
        user_id=user.get("sub")
    )
    db.add(new_project)
    db.commit()
    db.refresh(new_project)
    return {
        "id": new_project.id,
        "name": new_project.name,
        "user_id": new_project.user_id,
        "created_at": new_project.created_at.isoformat()
    }

@projects_router.get("")
async def list_projects(user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    user_projects = db.query(ProjectModel).filter(ProjectModel.user_id == uid).all()
    return [
        {
            "id": p.id,
            "name": p.name,
            "user_id": p.user_id,
            "created_at": p.created_at.isoformat()
        }
        for p in user_projects
    ]

# --- Specs Router ---
@specs_router.post("")
async def create_spec(payload: SpecCreate, user=Depends(get_current_user), db: Session = Depends(get_db)):
    new_spec = SpecModel(
        id=str(uuid.uuid4()),
        project_id=payload.project_id,
        title=payload.title,
        content=payload.content,
        source_type="manual",
        user_id=user.get("sub")
    )
    db.add(new_spec)
    db.commit()
    db.refresh(new_spec)
    return {
        "id": new_spec.id,
        "project_id": new_spec.project_id,
        "title": new_spec.title,
        "content": new_spec.content,
        "user_id": new_spec.user_id,
        "created_at": new_spec.created_at.isoformat()
    }

# --- Pipelines Router ---
@pipelines_router.get("/history")
async def get_pipelines_history(user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    user_runs = db.query(PipelineRunModel).filter(
        PipelineRunModel.user_id == uid,
        PipelineRunModel.status == "completed"
    ).order_by(PipelineRunModel.created_at.desc()).all()
    
    result = []
    for r in user_runs:
        spec_title = "Generated Specification"
        project_name = "Default Project"
        
        if r.spec_id:
            spec = db.query(SpecModel).filter(SpecModel.id == r.spec_id).first()
            if spec:
                spec_title = spec.title
                
        proj = db.query(ProjectModel).filter(ProjectModel.id == r.project_id).first()
        if proj:
            project_name = proj.name
            
        result.append({
            "id": r.id,
            "status": r.status,
            "created_at": r.created_at.isoformat() if r.created_at else "",
            "completed_at": r.completed_at.isoformat() if r.completed_at else "",
            "project_name": project_name,
            "spec_title": spec_title,
            "spec_id": r.spec_id,
            "duration_seconds": 15
        })
        
    return result

@pipelines_router.post("/run")
async def run_pipeline_job(
    payload: PipelineRunRequest, 
    response: Response, 
    background_tasks: BackgroundTasks,
    user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    uid = user.get("sub")
    logger.info(f"Running synchronous pipeline for user {uid}...")
    
    # 1. NLP Intent routing & extraction
    ir, confidence_score, rules, status = await run_nlp_pipeline(payload.spec_content)
    
    # 2. Agent Swarm debate cycles
    spec = await run_agent_swarm(
        ir=ir,
        rules=rules,
        prompt_used=payload.spec_content,
        parent_spec_id=payload.spec_id,
        confidence_score=confidence_score,
        generation_status=status
    )
    
    # 3. Dynamic schema mappings and code generation
    db_tables = []
    for table in spec.database.tables:
        db_tables.append({
            "name": table.name,
            "fields": [
                {
                    "name": col.name,
                    "type": col.type,
                    "constraints": ["primary_key"] if col.is_primary_key else ([] if col.is_nullable else ["not_null"])
                }
                for col in table.columns
            ]
        })
        
    api_endpoints = []
    for ep in spec.endpoints:
        api_endpoints.append({
            "method": ep.method,
            "path": ep.path,
            "desc": ep.summary,
            "errors": ep.error_responses if ep.error_responses else []
        })
        
    business_rules = []
    for r in spec.business_rules:
        business_rules.append({
            "name": r.rule,
            "type": "business_rule",
            "trigger_condition": r.reason
        })
        
    # Auto-deduct relationships from columns that have foreign keys
    relationships = []
    for table in spec.database.tables:
        for col in table.columns:
            if col.foreign_key:
                target_table = col.foreign_key.split(".")[0]
                relationships.append(f"{table.name}.{col.name} -> {target_table}.id")
                
    # Generate code skeletons & migrations
    code_skeleton = generate_code_skeleton(spec)
    migration_sql = generate_migration_sql(spec)
    
    result = {
        "summary": spec.spice.design_rationale,
        "entities": db_tables,
        "relationships": relationships,
        "join_tables": [],
        "endpoints": api_endpoints,
        "rules": business_rules,
        "code_skeleton": code_skeleton,
        "migration_sql": migration_sql,
        "anti_fragility": spec.anti_fragility.model_dump() if spec.anti_fragility else None,
        "__meta": {
            "source": "nvidia",
            "model": "meta/llama-3.3-70b-instruct",
            "spec_expansion": {
                "original_chars": len(payload.spec_content),
                "expanded_chars": len(payload.spec_content) * 3,
                "inferred_count": len(db_tables) + len(api_endpoints)
            }
        }
    }
    
    # Save the run history to SQL Database in the background
    run_id = str(uuid.uuid4())
    background_tasks.add_task(
        save_run_in_background,
        run_id,
        payload.project_id,
        payload.spec_id,
        uid,
        payload.spec_content,
        result
    )
        
    response.headers["x-baxel-generation-source"] = "nvidia"
    response.headers["x-baxel-generation-model"] = "meta/llama-3.3-70b-instruct"
    response.headers["x-baxel-plan-code"] = "studio"
    
    return {
        "id": run_id,
        "status": "completed",
        "result": result
    }

@pipelines_router.get("/{pipeline_id}")
async def get_pipeline_status(pipeline_id: str, user=Depends(get_current_user), db: Session = Depends(get_db)):
    uid = user.get("sub")
    run = db.query(PipelineRunModel).filter(
        PipelineRunModel.id == pipeline_id, 
        PipelineRunModel.user_id == uid
    ).first()
    if not run:
        raise HTTPException(status_code=404, detail="Pipeline run not found")
        
    return {
        "id": run.id,
        "project_id": run.project_id,
        "spec_id": run.spec_id,
        "user_id": run.user_id,
        "status": run.status,
        "result": run.result,
        "created_at": run.created_at.isoformat() if isinstance(run.created_at, datetime.datetime) else str(run.created_at)
    }

# --- Runs Router ---
@runs_router.get("/{pipeline_id}/share")
async def share_run(pipeline_id: str, user=Depends(get_current_user)):
    return {"token": f"share-{pipeline_id}"}
