import uuid
import logging
import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, Response

from app.core.auth import get_current_user
from app.services.nlp.pipeline import run_nlp_pipeline
from app.services.agents.generation import run_agent_swarm
from app.core.db import get_db
from app.models.spec_db import SpecModel
from sqlalchemy.orm import Session

logger = logging.getLogger(__name__)

# Global in-memory DB to store user sessions, projects, specs, and runs during runtime
in_memory_db = {
    "projects": [],
    "specs": [],
    "runs": []
}

# -------------------------------------------------------------
# Request & Response Schemas
# -------------------------------------------------------------

class ProjectCreate(BaseModel):
    name: str

class SpecCreate(BaseModel):
    project_id: str
    title: str
    content: str

class PipelineRunRequest(BaseModel):
    project_id: str
    spec_id: str
    stack: str = "fastapi+supabase"
    spec_content: str

# -------------------------------------------------------------
# Helpers
# -------------------------------------------------------------

def generate_code_skeleton(spec) -> Dict[str, str]:
    # Models skeleton
    models_code = "# SQLAlchemy models generated by Baxel\n\n"
    models_code += "from sqlalchemy import Column, String, Integer, DateTime, ForeignKey, Boolean\n"
    models_code += "from sqlalchemy.orm import relationship, declarative_base\n\nBase = declarative_base()\n\n"
    
    for table in spec.database.tables:
        models_code += f"class {table.name.title().replace('_', '')}(Base):\n"
        models_code += f"    __tablename__ = '{table.name}'\n"
        models_code += f"    # {table.description}\n\n"
        for col in table.columns:
            col_type = col.type.upper()
            if "UUID" in col_type:
                type_str = "String(36)"
            elif "INT" in col_type:
                type_str = "Integer"
            elif "DATE" in col_type or "TIME" in col_type:
                type_str = "DateTime"
            elif "BOOL" in col_type:
                type_str = "Boolean"
            else:
                type_str = "String(255)"
                
            args = []
            if col.is_primary_key:
                args.append("primary_key=True")
            if not col.is_nullable:
                args.append("nullable=False")
            if col.foreign_key:
                args.append(f"ForeignKey('{col.foreign_key}')")
                
            args_str = ", ".join(args)
            models_code += f"    {col.name} = Column({type_str}{', ' + args_str if args_str else ''})\n"
        models_code += "\n"
        
    # Routers skeleton
    routers_code = "# FastAPI routers generated by Baxel\n\n"
    routers_code += "from fastapi import APIRouter, Depends, HTTPException\n"
    routers_code += "from typing import List\n\nrouter = APIRouter()\n\n"
    
    for ep in spec.endpoints:
        normalized_name = ep.summary.lower().replace(" ", "_").replace("/", "_").replace("-", "_")
        routers_code += f"@router.{ep.method.lower()}('{ep.path}', summary='{ep.summary}')\n"
        routers_code += f"async def {normalized_name}(\n"
        if ep.is_protected:
            routers_code += "    current_user = Depends(get_current_user)\n"
        routers_code += "):\n"
        routers_code += f"    # TODO: Implement endpoint\n"
        routers_code += f"    return {{'message': '{ep.summary}'}}\n\n"
        
    return {
        "models": models_code,
        "routers": routers_code,
        "services": "# Business logic & helpers\n"
    }

def generate_migration_sql(spec) -> str:
    sql = "-- DB migration script generated by Baxel\n\n"
    for table in spec.database.tables:
        sql += f"CREATE TABLE IF NOT EXISTS {table.name} (\n"
        cols = []
        for col in table.columns:
            col_type = col.type.upper()
            if "UUID" in col_type:
                db_type = "UUID"
            elif "INT" in col_type:
                db_type = "INTEGER"
            elif "DATE" in col_type or "TIME" in col_type:
                db_type = "TIMESTAMP"
            elif "BOOL" in col_type:
                db_type = "BOOLEAN"
            else:
                db_type = "VARCHAR(255)"
                
            constraints = []
            if col.is_primary_key:
                constraints.append("PRIMARY KEY")
            if not col.is_nullable:
                constraints.append("NOT NULL")
            if col.foreign_key:
                constraints.append(f"REFERENCES {col.foreign_key.split('.')[0]}(id)")
                
            cols.append(f"    {col.name} {db_type} {' '.join(constraints)}".strip())
        sql += ",\n".join(cols)
        sql += "\n);\n\n"
    return sql

# -------------------------------------------------------------
# Routers definition
# -------------------------------------------------------------

projects_router = APIRouter(prefix="/projects", tags=["projects"])
specs_router = APIRouter(prefix="/specs", tags=["specs"])
pipelines_router = APIRouter(prefix="/pipelines", tags=["pipelines"])
dashboard_router = APIRouter(prefix="/dashboard", tags=["dashboard"])
profile_router = APIRouter(prefix="/profile", tags=["profile"])
runs_router = APIRouter(prefix="/runs", tags=["runs"])

# --- Profile Router ---
@profile_router.get("/me")
async def profile_me(user=Depends(get_current_user)):
    return {
        "id": user.get("sub"),
        "email": user.get("email"),
        "username": user.get("email", "user").split("@")[0],
        "full_name": user.get("email", "User").split("@")[0].title(),
        "avatar_url": None
    }

@profile_router.get("/plan")
async def profile_plan(user=Depends(get_current_user)):
    return {
        "plan_code": "studio",
        "plan_name": "Studio Plan",
        "status": "active",
        "monthly_run_limit": 100,
        "runs_used_this_month": len([r for r in in_memory_db["runs"] if r.get("user_id") == user.get("sub")]),
        "monthly_project_limit": 100,
        "projects_used_this_month": len([p for p in in_memory_db["projects"] if p.get("user_id") == user.get("sub")]),
        "runs_per_project_limit": 100,
        "idea_char_limit": 9000
    }

# --- Dashboard Router ---
@dashboard_router.get("/summary")
async def dashboard_summary(user=Depends(get_current_user)):
    uid = user.get("sub")
    user_projects = [p for p in in_memory_db["projects"] if p.get("user_id") == uid]
    user_runs = [r for r in in_memory_db["runs"] if r.get("user_id") == uid]
    
    # Enrich recent pipeline runs with spec_title and project_name
    enriched_runs = []
    for r in user_runs[-5:]:  # last 5 runs
        spec_title = "Generated Specification"
        project_name = "Default Project"
        
        spec = next((s for s in in_memory_db["specs"] if s["id"] == r["spec_id"]), None)
        if spec:
            spec_title = spec["title"]
            
        proj = next((p for p in in_memory_db["projects"] if p["id"] == r["project_id"]), None)
        if proj:
            project_name = proj["name"]
            
        enriched_runs.append({
            "id": r["id"],
            "status": r["status"],
            "created_at": r["created_at"],
            "spec_title": spec_title,
            "project_name": project_name,
            "spec_id": r["spec_id"]
        })
        
    return {
        "projects_count": len(user_projects),
        "specs_count": len([s for s in in_memory_db["specs"] if s.get("user_id") == uid]),
        "pipeline_runs_count": len(user_runs),
        "recent_projects": user_projects[-5:],  # last 5 projects
        "recent_pipeline_runs": enriched_runs[::-1]  # reverse to show newest first
    }

@dashboard_router.get("/public-metrics")
async def dashboard_public_metrics():
    return {
        "specs_processed": max(15, len(in_memory_db["specs"])),
        "schemas_generated": max(12, len(in_memory_db["runs"])),
        "api_endpoints": 96,
        "rules_captured": 45
    }

# --- Projects Router ---
@projects_router.post("")
async def create_project(payload: ProjectCreate, user=Depends(get_current_user)):
    new_project = {
        "id": str(uuid.uuid4()),
        "name": payload.name,
        "user_id": user.get("sub"),
        "created_at": datetime.datetime.utcnow().isoformat()
    }
    in_memory_db["projects"].append(new_project)
    return new_project

@projects_router.get("")
async def list_projects(user=Depends(get_current_user)):
    return [p for p in in_memory_db["projects"] if p.get("user_id") == user.get("sub")]

# --- Specs Router ---
@specs_router.post("")
async def create_spec(payload: SpecCreate, user=Depends(get_current_user)):
    new_spec = {
        "id": str(uuid.uuid4()),
        "project_id": payload.project_id,
        "title": payload.title,
        "content": payload.content,
        "user_id": user.get("sub"),
        "created_at": datetime.datetime.utcnow().isoformat()
    }
    in_memory_db["specs"].append(new_spec)
    return new_spec

# --- Pipelines Router ---
@pipelines_router.post("/run")
async def run_pipeline_job(
    payload: PipelineRunRequest, 
    response: Response, 
    user=Depends(get_current_user),
    db: Session = Depends(get_db)
):
    uid = user.get("sub")
    logger.info(f"Running synchronous pipeline for user {uid}...")
    
    # 1. NLP Intent routing & extraction
    ir, confidence_score, rules, status = await run_nlp_pipeline(payload.spec_content)
    
    # 2. Agent Swarm debate cycles
    spec = await run_agent_swarm(
        ir=ir,
        rules=rules,
        prompt_used=payload.spec_content,
        parent_spec_id=payload.spec_id,
        confidence_score=confidence_score,
        generation_status=status
    )
    
    # 3. Dynamic schema mappings and code generation
    db_tables = []
    for table in spec.database.tables:
        db_tables.append({
            "name": table.name,
            "fields": [
                {
                    "name": col.name,
                    "type": col.type,
                    "constraints": ["primary_key"] if col.is_primary_key else ([] if col.is_nullable else ["not_null"])
                }
                for col in table.columns
            ]
        })
        
    api_endpoints = []
    for ep in spec.endpoints:
        api_endpoints.append({
            "method": ep.method,
            "path": ep.path,
            "desc": ep.summary,
            "errors": ep.error_responses if ep.error_responses else []
        })
        
    business_rules = []
    for r in spec.business_rules:
        business_rules.append({
            "name": r.rule,
            "type": "business_rule",
            "trigger_condition": r.reason
        })
        
    # Auto-deduct relationships from columns that have foreign keys
    relationships = []
    for table in spec.database.tables:
        for col in table.columns:
            if col.foreign_key:
                target_table = col.foreign_key.split(".")[0]
                relationships.append(f"{table.name}.{col.name} -> {target_table}.id")
                
    # Generate code skeletons & migrations
    code_skeleton = generate_code_skeleton(spec)
    migration_sql = generate_migration_sql(spec)
    
    result = {
        "summary": spec.spice.design_rationale,
        "entities": db_tables,
        "relationships": relationships,
        "join_tables": [],
        "endpoints": api_endpoints,
        "rules": business_rules,
        "code_skeleton": code_skeleton,
        "migration_sql": migration_sql,
        "anti_fragility": spec.anti_fragility.model_dump() if spec.anti_fragility else None,
        "__meta": {
            "source": "nvidia",
            "model": "meta/llama-3.1-70b-instruct",
            "spec_expansion": {
                "original_chars": len(payload.spec_content),
                "expanded_chars": len(payload.spec_content) * 3,
                "inferred_count": len(db_tables) + len(api_endpoints)
            }
        }
    }
    
    # Save the generated spec to DB for chatbot/history query
    try:
        existing_spec = db.query(SpecModel).filter(SpecModel.id == payload.spec_id).first()
        if not existing_spec:
            db_spec = SpecModel(
                id=payload.spec_id,
                parent_spec_id=None,
                version=1,
                prompt_used=payload.spec_content,
                generated_json=spec.model_dump()
            )
            db.add(db_spec)
            db.commit()
            logger.info(f"Successfully saved spec {payload.spec_id} to SQL database.")
        else:
            existing_spec.generated_json = spec.model_dump()
            db.commit()
            logger.info(f"Successfully updated spec {payload.spec_id} in SQL database.")
    except Exception as db_err:
        logger.error(f"Failed to save generated spec to database: {db_err}")

    # 4. Save the run history to in_memory_db
    run_id = str(uuid.uuid4())
    new_run = {
        "id": run_id,
        "project_id": payload.project_id,
        "spec_id": payload.spec_id,
        "user_id": uid,
        "status": "completed",
        "result": result,
        "created_at": datetime.datetime.utcnow().isoformat()
    }
    in_memory_db["runs"].append(new_run)
    
    response.headers["x-baxel-generation-source"] = "nvidia"
    response.headers["x-baxel-generation-model"] = "meta/llama-3.1-70b-instruct"
    response.headers["x-baxel-plan-code"] = "studio"
    
    return {
        "id": run_id,
        "status": "completed",
        "result": result
    }

@pipelines_router.get("/{pipeline_id}")
async def get_pipeline_status(pipeline_id: str, user=Depends(get_current_user)):
    uid = user.get("sub")
    run = next((r for r in in_memory_db["runs"] if r["id"] == pipeline_id and r["user_id"] == uid), None)
    if not run:
        raise HTTPException(status_code=404, detail="Pipeline run not found")
    return run

# --- Runs Router ---
@runs_router.get("/{pipeline_id}/share")
async def share_run(pipeline_id: str, user=Depends(get_current_user)):
    return {"token": f"share-{pipeline_id}"}
